name = "Milvus"
uuid = "44452278-9d71-41a2-beb9-a0924b70c13d"
authors = ["zsz00 <zsz6174@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
